"use client";

import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, ArrowUpRight, Braces, Code2, ExternalLink, MapPin, Moon, Send, Sparkles, Sun, Terminal } from "lucide-react";
import { experience, projects, site, skills, stats } from "@/data/content";

const rise = { hidden: { opacity: 0, y: 20 }, show: { opacity: 1, y: 0, transition: { duration: .55, ease: [.22, 1, .36, 1] } } };
const Reveal = ({ children, className = "" }: { children: React.ReactNode; className?: string }) => <motion.div className={className} variants={rise} initial="hidden" whileInView="show" viewport={{ once: true, amount: .18 }}>{children}</motion.div>;

export default function Portfolio() {
  const [dark, setDark] = useState(true); const [loaded, setLoaded] = useState(false); const [dragging, setDragging] = useState(false); const rail = useRef<HTMLElement>(null); const drag = useRef({ startX: 0, startLeft: 0 });
  useEffect(() => { document.documentElement.dataset.theme = dark ? "dark" : "light"; }, [dark]);
  useEffect(() => { const reduced = matchMedia("(prefers-reduced-motion: reduce)").matches; const timer = setTimeout(() => setLoaded(true), reduced ? 0 : 600); const el = rail.current; const onWheel = (event: WheelEvent) => { if (!el || innerWidth <= 760 || reduced) return; event.preventDefault(); el.scrollLeft += event.deltaY + event.deltaX; }; el?.addEventListener("wheel", onWheel, { passive: false }); return () => { clearTimeout(timer); el?.removeEventListener("wheel", onWheel); }; }, []);
  return <main className={loaded ? "loaded" : ""}>
    <div className="preloader"><Code2 size={22} /> BHRUGU.VARIA</div>
    <nav><a className="brand" href="#home">BV<span>_</span></a><div className="links">{["home", "about", "experience", "projects", "skills", "contact"].map((item, i) => <a href={`#${item}`} key={item}><small>0{i + 1}</small>{item}</a>)}</div><button aria-label="Toggle colour theme" onClick={() => setDark(!dark)}>{dark ? <Sun size={16} /> : <Moon size={16} />}</button></nav>
    <aside className="scroll-hint"><span>SCROLL / DRAG</span><i /><span>→</span></aside>
    <div className="rail-controls" aria-label="Sideways scroll controls"><button onClick={() => rail.current?.scrollBy({ left: -innerWidth * .85, behavior: "smooth" })} aria-label="Scroll left">←</button><button onClick={() => rail.current?.scrollBy({ left: innerWidth * .85, behavior: "smooth" })} aria-label="Scroll right">→</button></div>
    <section className={`horiz-rail ${dragging ? "dragging" : ""}`} ref={rail} aria-label="Portfolio sections — scroll sideways on desktop" onWheel={event => { if (innerWidth <= 760) return; event.preventDefault(); event.currentTarget.scrollLeft += event.deltaY || event.deltaX; }} onPointerDown={event => { if (innerWidth <= 760) return; drag.current = { startX: event.clientX, startLeft: event.currentTarget.scrollLeft }; event.currentTarget.setPointerCapture(event.pointerId); setDragging(true); }} onPointerMove={event => { if (!dragging) return; event.currentTarget.scrollLeft = drag.current.startLeft - (event.clientX - drag.current.startX); }} onPointerUp={event => { if (!dragging) return; event.currentTarget.releasePointerCapture(event.pointerId); setDragging(false); }} onPointerCancel={() => setDragging(false)}>
      <section id="home" className="panel hero"><div className="grid" /><div className="glow" /><div className="hero-copy"><p className="eyebrow"><MapPin size={14} /> REGINA, SK, CANADA · <span>AVAILABLE_FOR_CO-OP</span></p><h1><span>AI systems.</span><span>Visual <em>stories.</em></span></h1><p>I’m Bhrugu — a Computer Science student focused on data analytics, IT support, and business technology. I build reliable dashboards, automation systems, and useful interfaces.</p><div className="actions"><a className="primary" href="#projects">View builds <ArrowRight size={17} /></a><a href="#contact">Start a conversation <Send size={15} /></a></div></div><div className="terminal-card" aria-label="Terminal showing profile information"><div className="terminal-head"><span /><span /><span /><b>~/bhrugu/portfolio</b></div><p><i>$</i> whoami</p><strong>bhrugu_varia</strong><p><i>$</i> cat focus.txt</p><span>DATA · AUTOMATION · IT OPS</span><p><i>$</i> status</p><mark><b /> open_to_work</mark><p className="cursor"><i>$</i> _</p></div><div className="side-scroll-label" aria-hidden="true"><span>←</span><i /><b>SCROLL SIDEWAYS</b><i /><span>→</span></div></section>
      <section id="about" className="panel about-panel"><header className="panel-title"><p className="eyebrow">01 — PROFILE.MD</p><h2>Logic with a<br /><em>human layer.</em></h2></header><div className="about-layout"><Reveal><div className="bio"><p>I’m a B.Sc. Computer Science student at the University of Regina, working at the intersection of data analytics, IT support, and business technology. My experience spans ETL workflows, interactive dashboards, transaction processing, client data, and AI-powered automation—always with a focus on accuracy and clear communication.</p><p>I enjoy turning operational data into useful systems. As founder of <a href={site.illustrator} target="_blank">_theilluminator ↗</a>, I also use illustration and campaign design as tools for connection.</p><p className="current"><Sparkles size={16} /><b>NOW_RUNNING:</b> Front End Assistant at Costco Wholesale · Seeking co-op roles in data, IT, and business technology</p></div></Reveal><Reveal><aside className="facts"><div className="facts-head"><Braces size={20} /><span>QUICK_FACTS.JSON</span></div><code>{`{\n  location: "Regina, SK",\n  program: "U of R Computer Science",\n  focus: ["data", "automation", "IT operations"]\n}`}</code></aside></Reveal></div><div className="stats">{stats.map((stat, i) => <Reveal key={stat.label}><small>METRIC_0{i + 1}</small><strong>{stat.value}</strong><span>{stat.label}</span></Reveal>)}</div></section>
      <section id="experience" className="panel experience-panel"><header className="panel-title"><p className="eyebrow">02 — GIT LOG / EXPERIENCE</p><h2>Things I’ve<br /><em>shipped.</em></h2></header><div className="experience-list">{experience.map((item, i) => <Reveal className="job" key={item.company}><div className="job-index">0{i + 1}<span /></div><article><p className="period">{item.period} · {item.place}</p><h3>{item.role}</h3><h4>{item.company}</h4><ul>{item.points.map(point => <li key={point}>{point}</li>)}</ul></article></Reveal>)}</div><Reveal className="lead"><span>LEADERSHIP_COMMIT · 2024</span><h3>Marketing Head — Diwali Gala</h3><p>Led budget tracking, vendor coordination, sponsorship procurement, and financial reporting for a 200+ attendee event.</p></Reveal></section>
      <section id="projects" className="panel projects-panel"><header className="panel-title"><p className="eyebrow">03 — REPOSITORIES</p><h2>Systems, stories,<br /><em>signals.</em></h2><p className="project-intro">Selected builds at the intersection of technology, financial clarity, and visual expression.</p></header><div className="cards">{projects.map(project => <Reveal key={project.title}><article className={`card ${project.style}`}><div className="art"><span>{project.num}</span><i /><i /><i /><code>&lt;/&gt;</code></div><div className="cardcopy"><p className="eyebrow">{project.type}</p><h3>{project.title}</h3><p>{project.text}</p><ul>{project.items.map(item => <li key={item}>{item}</li>)}</ul><footer><div>{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><a href={project.url} target={project.url.startsWith("http") ? "_blank" : undefined}>Open <ArrowUpRight size={17} /></a></footer></div></article></Reveal>)}</div></section>
      <section id="skills" className="panel skills-panel"><header className="panel-title"><p className="eyebrow">04 — STACK.TRACE</p><h2>Fluent across<br /><em>the stack.</em></h2></header><div className="skillset">{skills.map((group, i) => <Reveal className="skill" key={group.title}><span>0{i + 1}</span><h3>{group.title}</h3><div>{group.items.map(item => <b key={item}>{item}</b>)}</div></Reveal>)}</div><div className="binary-strip">01000010 01010110 · BUILDING INTERFACES / AUTOMATING THE REPETITIVE / LEARNING IN PUBLIC · 01000010 01010110</div></section>
      <section id="contact" className="panel contact"><div><p className="eyebrow">05 — CONNECT()</p><h2>Let’s build<br /><em>something.</em></h2><p>Open to co-op placements, internships, and interesting projects.</p><a className="email" href={`mailto:${site.email}`}><Terminal size={19} />{site.email}<ArrowUpRight size={20} /></a><div className="social"><a href={site.linkedin} target="_blank">LinkedIn <ExternalLink size={14} /></a><a href={site.illustrator} target="_blank">_theilluminator <ExternalLink size={14} /></a></div></div><footer className="sitefooter"><span>© 2026 Bhrugu Varia</span><span>Next.js · TypeScript · Motion</span><a href="#home">return_to_start()</a></footer></section>
    </section>
  </main>;
}
